---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: my-namespace-role--read-only
    namespace: my-namespace
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: my-service-account
    namespace: my-namespace

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: my-namespace-role-binding--read-only
    namespace: my-namespace
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: my-namespace-role--read-only
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: ServiceAccount
    name: my-service-account
    namespace: my-namespace
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: my-user
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: my-group
