---
apiVersion: v1
kind: Secret
metadata:
    labels: {app: my-app}
    name: my-app-secret
    namespace: my-namespace
type: Opaque
stringData:
    SECRET_ENV: my-secret-env-value
    SECRET_FILE: |
        {
            "key_01": "value_02",
            "key_02": "value_02",
        }
