---
apiVersion: v1
kind: PersistentVolume
metadata:
    labels: {app: my-app}
    name: my-pv
    namespace: my-namespace
spec:
    storageClassName: manual
    hostPath: {path: "/opt/volumes/my-pv"}
    capacity: {storage: 10Gi}
    accessModes: [ReadWriteOnce]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels: {app: my-app}
    name: my-pvc
    namespace: my-namespace
spec:
    storageClassName: manual
    selector: {matchLabels: {type: my-app}}
    resources: requests: {storage: 10Gi}
    accessModes: [ReadWriteOnce]
