#!/bin/sh

# Usage:
# $ kubectl shell

# set -x # verbose
set -o pipefail # exit on pipeline error
set -e # exit on error
set -u # variable must exist

IMAGE=${1:-bash}

kubectl run --rm -it shell --generator=run-pod/v1 --image="${IMAGE}"
