#!/bin/zsh

# Usage:
# $ goto number

# set -x # verbose
set -o pipefail # exit on pipeline error
set -e # exit on error
set -u # variable must exist


local paths=("${(f)$(< ~/.goto)}")
local key
if (( $ARGC == 1 )); then
    key=${1}
else
    for (( i = 1; i <= $#paths; i++ )) do
        echo $i - "${paths[$i]}"
    done
    read -sk1 key
fi
cd "${paths[$key]}"
