#!/bin/bash

# Usage:
# make-self-cacert "hellupline.dev"

# set -x # verbose
set -o pipefail # exit on pipeline error
set -e # exit on error
set -u # variable must exist

DOMAIN=${1:-localhost}

mkdir -p tls-certs

# create rootca certs
openssl genrsa -out tls-certs/rootca.key 4096
openssl req -x509 -new -sha256 -days 3650 \
    -key tls-certs/rootca.key -out tls-certs/rootca.cert \
    -subj "/O=${DOMAIN}/CN=${DOMAIN}"

# create application certs
openssl genrsa -out tls-certs/service.key 4096
openssl req -new -sha256 -days 3650 \
    -addext "subjectAltName = DNS:${DOMAIN},IP:::1,IP:127.0.0.1" \
    -key tls-certs/service.key -out tls-certs/service.csr \
    -subj "/O=${DOMAIN}/CN=${DOMAIN}"
openssl x509 -req -sha256 \
    -CA tls-certs/rootca.cert -CAkey tls-certs/rootca.key -CAcreateserial \
    -in tls-certs/service.csr -out tls-certs/service.pem \
    -extfile <( \
        echo 'authorityKeyIdentifier=keyid,issuer'; \
        echo 'basicConstraints=CA:FALSE'; \
        echo 'keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment'; \
        echo "subjectAltName = DNS:${DOMAIN},IP:::1,IP:127.0.0.1"; \
    )
