#! /usr/bin/env python3


from http.server import HTTPServer, SimpleHTTPRequestHandler
from functools import partial
from ssl import wrap_socket

CERT_FILE = "tls-certs/service.pem"
DIRECTORY = "./"

handler = partial(SimpleHTTPRequestHandler, directory=DIRECTORY)
httpd = HTTPServer(("localhost", 4443), handler)
httpd.socket = wrap_socket(httpd.socket, certfile=CERT_FILE, server_side=True)
httpd.serve_forever()
