#!/bin/sh

# Usage:
# $ wallpapers

# set -x # verbose
set -o pipefail # exit on pipeline error
set -e # exit on error
set -u # variable must exist

SOURCES=(
        ~/wallpapers/artstation
        ~/wallpapers/meh.ro
)
SLEEP="60"

while true; do
    feh --recursive --randomize --bg-max --no-fehbg \
        ${SOURCES[@]}
    sleep "${SLEEP}"
done
