---
apiVersion: v1
kind: Service
metadata:
    labels: {app: my-app}
    name: my-app-service
    namespace: my-namespace
spec:
    ports:
      - {name: http, protocol: TCP, port: 80, targetPort: 80}

---
apiVersion: v1
kind: Endpoints
metadata:
    labels: {app: my-app}
    name: my-app-service
    namespace: my-namespace
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 9376
